export const PHRASAL_VERBS = [
  {
    verb: "look up",
    meaning: "to search for information",
    example: "If you don't know the word, look it up in the dictionary.",
    particles: ["up"],
    tags: ["study", "information"],
  },
  {
    verb: "turn on",
    meaning: "to start a machine or light",
    example: "Please turn on the lights; it's getting dark.",
    particles: ["on"],
    tags: ["home", "everyday"],
  },
  {
    verb: "turn off",
    meaning: "to stop a machine or light",
    example: "Don't forget to turn off the TV before bed.",
    particles: ["off"],
    tags: ["home", "everyday"],
  },
  {
    verb: "pick up",
    meaning: "to collect someone or something",
    example: "I'll pick you up at the station at 7.",
    particles: ["up"],
    tags: ["travel", "everyday"],
  },
  {
    verb: "put off",
    meaning: "to delay something to a later time",
    example: "We had to put off the meeting until next week.",
    particles: ["off"],
    tags: ["work", "planning"],
  },
  {
    verb: "give up",
    meaning: "to stop doing something",
    example: "She gave up smoking last year.",
    particles: ["up"],
    tags: ["health", "habits"],
  },
  {
    verb: "run into",
    meaning: "to meet someone by chance",
    example: "I ran into an old friend at the supermarket.",
    particles: ["into"],
    tags: ["people", "everyday"],
  },
  {
    verb: "look after",
    meaning: "to take care of someone or something",
    example: "Can you look after my cat while I'm away?",
    particles: ["after"],
    tags: ["care", "home"],
  },
  {
    verb: "set up",
    meaning: "to arrange or establish something",
    example: "They set up a new company last year.",
    particles: ["up"],
    tags: ["business", "work"],
  },
  {
    verb: "break down",
    meaning: "(of a machine) to stop working",
    example: "Our car broke down on the way to the airport.",
    particles: ["down"],
    tags: ["travel", "problems"],
  },
  {
    verb: "carry on",
    meaning: "to continue",
    example: "Carry on with your work while I make a call.",
    particles: ["on"],
    tags: ["work", "everyday"],
  },
  {
    verb: "find out",
    meaning: "to discover information",
    example: "I need to find out what time the train leaves.",
    particles: ["out"],
    tags: ["study", "information"],
  },
  {
    verb: "work out",
    meaning: "to exercise OR to solve a problem (context-dependent)",
    example: "We need to work out how to reduce costs.",
    particles: ["out"],
    tags: ["health", "problem-solving"],
  },
  {
    verb: "bring up",
    meaning: "to mention a topic or to raise a child",
    example: "She brought up an interesting point in the meeting.",
    particles: ["up"],
    tags: ["conversation", "work"],
  },
  {
    verb: "get along",
    meaning: "to have a good relationship",
    example: "Do you get along with your neighbors?",
    particles: ["along"],
    tags: ["people", "relationships"],
  },
  {
    verb: "hand in",
    meaning: "to submit (homework, assignment)",
    example: "Please hand in your assignments by Friday.",
    particles: ["in"],
    tags: ["school", "work"],
  },
  {
    verb: "check out",
    meaning: "to look at or examine; to pay and leave a hotel",
    example: "Check out this new website when you have time.",
    particles: ["out"],
    tags: ["travel", "everyday"],
  },
  {
    verb: "catch up",
    meaning: "to reach the same level or standard",
    example: "I need to catch up on emails after my vacation.",
    particles: ["up"],
    tags: ["work", "time"],
  },
  {
    verb: "sort out",
    meaning: "to organize or resolve a problem",
    example: "Let's sort out the seating plan before the event.",
    particles: ["out"],
    tags: ["organization", "problem-solving"],
  },
  {
    verb: "look forward to",
    meaning: "to feel excited about something that will happen",
    example: "I look forward to seeing you soon.",
    particles: ["forward", "to"],
    tags: ["feelings", "future"],
  },
];
